config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  # resources :users do
  #   resources :categories do
  #     resources :be_transactions
  #   end
  # end

  # resources :users, only: [:create, :show, :index] 
  resources :categories, only: [:index, :show, :create, :new] do
    resources :expenses, only:[:index, :show, :create, :new]
  end
  # resources :be_transactions, only: [:index, :show, :create, :new]
  # resources :be_transactions, only: [:index, :show, :create, :new]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses
  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, dependent: :destroy, foreign_key: :user_id
  has_many :categories, dependent: :destroy, foreign_key: :user_id
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    categories_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:name, :email, :password, :remember_me)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new, status: 422
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])

    if @category.user == current_user
      @expense = Expense.new
    else
      flash[:alert] = 'You can only create expenses from your categories'
      redirect_to categories_path
    end
  end

  def create
    @category = Category.find(params[:category_id])
    if @category.user != current_user
      flash[:alert] = 'You can only create expenses from your categories'
      redirect_to categories_path
    end
    if expense_params[:category_ids].length == 1
      flash[:alert] = 'Must select at least one category'
      redirect_to new_category_expense_path(@category)
    else
      @category = Category.find(params[:category_id])
      @expense = Expense.new(expense_params)
      @expense.user = current_user

      if @expense.save
        flash[:notice] = 'Expense was created successfully'
        redirect_to @category
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/users_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/be_transactons_helper.rb
module BeTransactonsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/be_transactons/new.html.erb
<p class="text-center fs-2 fw-bold">Categories Registration</p>

<%= form_with url: be_transactions_path, model: @be_transaction, method: :post, class: 'p-2 m-4' do |f|%>
  <%if @category.errors.any?%>

    <div class='alert alert-danger'>
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>

    <% @be_transaction.errors.full_messages.each do |msg|%>
      <p><%=msg%></p>
     <%end%>
    </div>
  <%end%>
  <div class="mb-2 g-2">
  <%= f.label :be_transaction, "Transaction Name ", class: "col-sm-2 col-form-label form-label fs-4 fw-bold" %>
    <div class="col-sm-10">
    <%= f.text_field :name, required:true, class: "form-control form-control-lg form-control-sm", placeholder: 'Eg. Alzormi '%>
    </div>
  </div>

    <div class="mb-2 g-2">
  <%= f.label :be_transaction, "Transaction Amount ", class: "col-sm-2 col-form-label form-label fs-4 fw-bold" %>
    <div class="col-sm-10">
    <%= f.text_field :amount, required:true, class: "form-control form-control-lg form-control-sm", placeholder: 'Eg. Alzormi '%>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary'%>
<%end%>

app/views/categories/index.html.erb
<div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
  <h1 class="mb-3">Categories</h1>

  <div>
    <% @categories.each do |category| %>
      <div class="card mb-1">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <img src="<%= category.icon %>" width=60 height=60 , class= 'col-4 py-1'>
            </div> 
            <div class="col">
              <%= link_to category.name, category_path(category) %>
            </div>
            <div class="col">
              $<%= category.expenses.sum(:amount) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Add new category", new_category_path, class: "btn btn-success mt-3" %>
</div>

app/views/categories/new.html.erb
<div class="d-flex flex-column justify-content-between align-items-between">
<p class="text-center fs-2 fw-bold">Categories Registration</p>

<%= form_with url: categories_path, model: @category, method: :post, class: 'p-2 m-4' do |f|%>
  <%if @category.errors.any?%>

    <div class='alert alert-danger'>
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>

    <% @category.errors.full_messages.each do |msg|%>
      <p><%=msg%></p>
     <%end%>
    </div>
  <%end%>
    <%= form_with model: @category, class: "d-flex flex-column justify-content-between align-items-between" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :icon, class: "form-label" %>
      <%= form.text_field :icon, class: "form-control", placeholder: "Icon URL" %>
    </div>

    <%= form.submit class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back", categories_path, class: "btn btn-secondary mt-2" %>
<%end%>

app/views/categories/show.html.erb
<div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
  <div class="row">
    <div class="col-8">
      <h2><%= @category.name %></h2>
    </div>
    <div class="col-4">
      <p>$<%= @total %></p>
    </div>
  </div>

    <div>
    <% @expenses.each do |expense| %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="row">
            <div class="col-8">
              <%= expense.name %>
            </div>
            <div class="col-4">
              $<%= expense.amount %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
    <div class="d-flex flex-column justify-content-between align-items-between">
    <%= link_to "Add new expense", new_category_expense_path(@category), class: "btn btn-success" %> <br>
    <%= link_to "Back", categories_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/expenses/index.html.erb
<%= stylesheet_link_tag "category_controller" %>

<div class="conatiner">
<table class="table table-striped">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Amount</th>
    </tr>

    <% @expenses.each do |expense| %>
      <tr>
      <td scope="row"><%= expense.name%></td>
      <td scope="row"><%= expense.amount%></td>
     </tr>
    <% end %>
</table>
<%=link_to "Add Expense",expenses_new_path, class: "btn btn-primary"%>
</div>

app/views/expenses/new.html.erb
<div class="d-flex flex-column justify-content-between align-items-between">
 
  <%= form_with model: @expense, url: category_expenses_path, class: "d-flex flex-column justify-content-between align-items-between" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :amount, class: "form-label" %>
      <%= form.number_field :amount, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.collection_select(:category_ids, current_user.categories, :id, :name, {}, { multiple: true, size: 7, class: "form-select" }) %>
    </div>

    <%= form.submit class: "btn btn-primary" %>

  <% end %>

  <%= link_to "Back", category_path(@category), class: "btn btn-secondary mt-2" %>
</div>

app/views/home/index.html.erb
<div class="container w-25 d-flex flex-column align-items-center p-3 mx-auto">
  <h1 class="mb-5">Budget App</h1>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-warning mb-2" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary mb-2" %><br>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </head>

  <body>
 <%=render "shared/header"%>
   <%if flash[:notice]%>
    <p class="notice alert alert-info"><%= notice %></p>
   <%end%>

   <%if flash[:alert]%>
        <p class="alert alert-danger"><%= alert %></p>
   <%end%>
   
    <%= yield %>
 <%=render "shared/footer"%>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer class='bg-dark text-white  text-center p-2'>
<p>Budget App Designed by <br/></p>
<div>
<%= link_to 'Bantealem Geto', 'https://github.com/Bantealem', class: 'btn btn-text text-white'%>
</div>

<strong>
 Copyright &copy;2023
</strong>
</footer>

app/views/shared/_header.html.erb
 <nav class="navbar navbar-expand-md navbar-dark bg-primary p-2">
  <div class="collapse navbar-collapse d-flex justify-content-between align-items-center" id="navbarColor01">
  <ul class="navbar-nav mr-auto">

  <li class="nav-item">
    <%= link_to 'Categories', categories_path, class: 'nav-link fs-5' %>
  </li>
</ul>

<ul class="navbar-nav d-flex align-items-center gap-2">
  <% if user_signed_in? %>
  <li class="nav-item">
     <span class='fs-5 text-white'><%= current_user.name%></span>
  </li>
   <li class="nav-item">
   <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-text text-white' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'Sign In', new_user_session_path, class: 'nav-link fs-5' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link fs-5' %>
    </li>
  <% end %>
 </ul>
  </div>
 </nav>